- request-api/Dockerfile
- request-api/src/crud.py
- request-api/src/main.py
- request-api/src/pagination_model.py
- request-api/tests/integration/test_main.py
- request-processor/Dockerfile
- request_model/models.py
- request_model/schemas.py
- Added new paginated endpoint for retrieving response details.
- Removed response details from request read endpoint
> Paginated response details

- docker-compose.yml
- request-api/Dockerfile
- request-api/src/main.py
- request-api/src/schema.py
- request-api/tests/integration/test_main.py
- request-api/tests/unit/test_main.py
- request-processor/docker-healthcheck.sh
- request-processor/healthcheck-output-template.json
Added healthcheck endpoint to request-api which has replaced the original hello world endpoint.
> Request API healthcheck

- .github/workflows/publish.yml
Added missing build-arg for GIT_COMMIT on request-api image build
> GIT_COMMIT build arg for request-api

- request-api/src/main.py
- request-api/tests/unit/test_main.py
Fix to set status code to 200 or 500 depending on health of dependencies
> Return correct status code when any dependencies are unhealthy

- .flake8
- request-processor/src/application/core/utils.py
- request-processor/src/application/core/workflow.py
- request-processor/src/tasks.py
- request-processor/tests/conftest.py
- request-processor/tests/integration/src/application/core/test_workflow.py
- request-processor/tests/unit/src/application/core/test_workflow.py
- request_model/schemas.py
Reference Ticket: https://trello.com/c/v75jAr6r/1406-depreciate-geomtype-parameter-and-add-columnmapping-parameter
Changes included:
- Adding column_mapping parameter
- Depreciating geom_type
- Adding test cases
- Fetching the specification files with list of all fields
- Updating the error summary in case mapping not found in specification
> Adding column-mapping parameter

- request-api/migrations/versions/d45c986e2727_create_indexes_for_foreign_keys.py
- request_model/models.py
Added indexes for foreign keys on response and response_details tables to improve query performance
Thanks for uncovering the problem @ssadhu-sl !
> Indexes for foreign keys on response and response_details tables

- request-api/src/main.py
Added exception logging to healthcheck endpoint on request-api
> Exception logging for healthcheck endpoint on request-api

- request-api/src/main.py
- request-processor/src/tasks.py
Added config to set Sentry debug option via environment variable
> Sentry debug config option

- README.md
- request-api/makefile
- request-api/tests/integration/test_main.py
- request-api/tests/unit/test_main.py
- request-processor/makerules/makerules.mk
- request-processor/makerules/python.mk
- request-processor/requirements/test_requirements.in
- request-processor/requirements/test_requirements.txt
- request-processor/tests/integration/src/test_tasks.py
- request-processor/tests/unit/src/application/core/test_workflow.py
- request-processor/tests/unit/src/test_tasks.py
Async service: Improve readability of request-processor integration tests
> Async test to improve readability

- request-processor/src/application/core/workflow.py
- request-processor/tests/integration/src/application/core/test_workflow.py
Updates tests to check for specific content
> Adds content checking to tests

- request-processor/tests/integration/src/application/core/test_workflow.py
> Modifying test case

- request-processor/src/application/configs/mapping.yaml
- request-processor/src/application/core/pipeline.py
Adds mappings for new mandatory fields for brownfield-land
https://trello.com/c/otLeEOAv/3565-brownfield-land-mandatory-fields
Can be tested by running locally and providing a brownfield land file
Only to be merged after cross-team brownfield land meeting
> add BFL mandatory fields

- .github/workflows/publish.yml
Update GHA workflow deploy as ecs service, remove duplicate task issue
- Ticket Link
- Closes #
_We encourage you to keep the code coverage percentage at 80% and above._
> Update GHA workflow deploy as ecs service

- request-api/Dockerfile
- request-processor/Dockerfile
- request-processor/docker-entrypoint.sh
- request-processor/docker-healthcheck.sh
Adding the required package for pgrep in dockerfile. Without this, the healthcheck was failing.
- Ticket Link: https://github.com/orgs/digital-land/projects/9?pane=issue&itemId=88539535&issue=digital-land%7Casync-request-backend%7C49
- Closes #
_We encourage you to keep the code coverage percentage at 80% and above._
> Updating docker image to slim-bookworm

- README.md
- request-processor/src/application/core/utils.py
- request-processor/src/application/core/workflow.py
- request-processor/src/tasks.py
- request-processor/tests/unit/src/application/core/test_utils.py
LPAs sometimes send arcgis link with multiple layers. Our API processes it like a normal data and give invalid response. We need to handle these better rather than giving back an invalid response.
- Ticket Link: https://github.com/orgs/digital-land/projects/9/views/14?pane=issue&itemId=90862159&issue=digital-land%7Csubmit%7C536
- Closes #
> Adding a check to validate URL for multiple layers in arcgis

- .github/workflows/test.yml
Simply adding an extra workflow that runs on all branches except main, this should be ran on PRs to ensure the code on them is tested
- Ticket Link
- Closes #
> add a test workflow

- request-processor/src/application/core/pipeline.py
remove temporary dir from pipeline as it's not needed.
- Ticket Link
- Closes #
> Remove temp dir

- request-api/requirements/requirements.txt
- request-api/src/main.py
This reverts commit fefaeb8df9f8d1475b06506f4f8a8fb98e9702b0.
Reverted the changes made in sentry connection closed error (#53) branch.
> Revert "Fix/sentry connection closed error (#53)"

- request-api/requirements/requirements.in
- request-api/requirements/requirements.txt
- request-api/requirements/test_requirements.txt
- request-api/src/main.py
- request-api/tests/integration/test_main.py
This PR resolve the test failures from the "fix/sentry-connection_closed_error" branch .
- Ticket Link: [ticket](https://github.com/orgs/digital-land/projects/9/views/14?filterQuery=-status%3A%22Ice+Box%22%2C%22Refine%2C+Prioritise+%26+Plan%22%2CBacklog%2C%22Done+-+This+Period%22%2C%22Analysis%2C+Research+%26+Design%22+team%3A%22Live+Service%22&visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Labels%22%2C141075453%2C123068832%2C%22Reviewers%22%2C%22Linked+pull+requests%22%2C%22Type%22%2C%22Sub-issues+progress%22%2C%22Parent+issue%22%5D&pane=issue&itemId=83936731&issue=digital-land%7Ctechnical-documentation%7C81)
- Closes: closed [PR](https://github.com/digital-land/async-request-backend/pull/53)
_Please replace this line with instructions on how to test your changes, …
> Fix/lint failure(sentry connection closed error)

- request-processor/requirements/requirements.in
- request-processor/requirements/requirements.txt
- request-processor/requirements/test_requirements.in
- request-processor/requirements/test_requirements.txt
- request-processor/src/application/configs/mapping.yaml
- request-processor/src/application/core/pipeline.py
- request-processor/src/application/core/workflow.py
- request-processor/tests/conftest.py
- request-processor/tests/unit/src/application/core/test_workflow.py
Added Invalid Category Value check to the async code. This was already done in digital-land-python and needed to be copied from there and tested.
- Ticket Link: https://github.com/orgs/digital-land/projects/9/views/14?pane=issue&itemId=104074210&issue=digital-land%7Csubmit%7C1003
- Closes #
> Invalid category check

- .github/workflows/test.yml
_Please replace this line with a brief description of the changes made._
- Ticket Link
- Closes #
> ensure python 3.10 installed

- .github/workflows/publish.yml
- .github/workflows/test.yml
_Please replace this line with a brief description of the changes made._
- Ticket Link
- Closes #
> correct workflows so the same testing is used
